#配置服务器端口
server:
  port: 9997
#配置数据库连接
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.95.198.82:3306/cms?useunicode=true;&characterEncoding=utf8
    username: root
    password: root